---
name: 'Checkout and Set Up Yarn'

description: 'Check out the repo, set up Node and Yarn with private registry support, and then install dependencies using Yarn.'

inputs:
  auth-token:
    description: 'Token for authenticating with GitHub Package Registry'
    required: true
  github-package-registry-scope:
    description: 'Package scope to point at GitHub Package Registry. (Defaults to owner of repository where action is being used)'
    default: ''
  node-version:
    description: 'Node version to force usage of. (Defaults to value found in .tool-versions, .nvmrc, or "16"'
    required: false
    default: ''
  fetch-depth:
    description: 'Number of commits to fetch. 0 indicates all history for all branches and tags.'
    required: false
    default: 1

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: ${{ inputs.fetch-depth }}

    - name: Get node version
      id: node-version
      shell: bash
      run: |
        if [ "${{ inputs.node-version }}" != "" ]; then
          NODE_VERSION=${{ inputs.node-version }}
        elif [ -f .tool-versions ]; then
          NODE_VERSION=$(cat .tool-versions | grep nodejs | cut -d' ' -f2)
        elif [ -f .nvmrc ]; then
          NODE_VERSION=$(cat .nvmrc | tr -d 'v')
        else
          NODE_VERSION="16"
        fi

        echo "::set-output name=node-version::${NODE_VERSION}"

    - uses: actions/setup-node@v2
      with:
        # cache: 'yarn'
        node-version: ${{ steps.node-version.outputs.node-version }}

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      shell: bash
      run: |
        echo "::set-output name=dir::$(yarn cache dir)"

    - name: install dependencies
      shell: bash
      run: |
        yarn install --frozen-lockfile --no-progress --non-interactive
      env:
        NODE_AUTH_TOKEN: ${{ inputs.auth-token }}
